### ISSUE TITLE
Actions运行失败，卡在Run node oracle.js

### ISSUE THREAD

**Issue by yburger** [TestSmirk/oracleLogin#6]
Tenant 7
UserName 13
Password 17
等待页面加载 
输入tenant
点击确定
等待下一页加载
(node:2389) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "#idcs-signin-basic-signin-form-username" failed: timeout 30000ms exceeded
    at new WaitTask (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/helper.js:112:23)
    at Frame.waitFor (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/FrameManager.js:612:19)
    at Page.waitFor (/home/runner/work/oracleLogin/oracleLogin/node_modules/puppeteer/lib/Page.js:1086:29)
    at /home/runner/work/oracleLogin/oracleLogin/oracle.js:29:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BitaminKim** [comment]
网络问题，最好手动改下oracle的代码里面的inputTypeSubmit的事件之后等待个30秒再让他继续跑

**Comment by fjweel** [comment]
> 网络问题，最好手动改下oracle的代码里面的inputTypeSubmit的事件之后等待个30秒再让他继续跑

请问怎么修改啊？纯小白，求赐教

**Comment by TestSmirk** [comment]
> > 网络问题，最好手动改下oracle的代码里面的inputTypeSubmit的事件之后等待个30秒再让他继续跑
> 
> 请问怎么修改啊？纯小白，求赐教
看[代码](https://github.com/TestSmirk/oracleLogin/blob/6fdab189d75511e92c471a27663b238d8a6aae32/oracle.js#L31) 现在改成30秒了。

**Comment by fjweel** [comment]
> > > 网络问题，最好手动改下oracle的代码里面的inputTypeSubmit的事件之后等待个30秒再让他继续跑
> > 
> > 
> > 请问怎么修改啊？纯小白，求赐教
> > 看[代码](https://github.com/TestSmirk/oracleLogin/blob/6fdab189d75511e92c471a27663b238d8a6aae32/oracle.js#L31) 现在改成30秒了。

运行了好几次，一直运行不动，像是卡在了输入密码过程中了，且运行到输入密码过程中并没有等待30秒，求大神赐教：
Run node oracle.js
Tenant 10
UserName 19
Password 13
等待页面加载 
输入tenant
点击确定
等待下一页加载
输入密码
(node:3538) UnhandledPromiseRejectionWarning: Error: No node found for selector: .oj-inputpassword-input
    at assert (/home/runner/work/oraclelogin/oraclelogin/node_modules/puppeteer/lib/helper.js:279:11)
    at DOMWorld.type (/home/runner/work/oraclelogin/oraclelogin/node_modules/puppeteer/lib/DOMWorld.js:421:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/work/oraclelogin/oraclelogin/oracle.js:46:5
  -- ASYNC --
    at Frame.<anonymous> (/home/runner/work/oraclelogin/oraclelogin/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.type (/home/runner/work/oraclelogin/oraclelogin/node_modules/puppeteer/lib/Page.js:1076:29)
    at /home/runner/work/oraclelogin/oraclelogin/oracle.js:46:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
